product-os/self-hosted-runners

versionist.conf.js

Correct versioning regex

---

runner/balena.sh

Support multiple instances

---

runner/balena.sh

Parametrise runner options

---

runner/Dockerfile

Fix permissions on all files in user home

---

runner/balena.sh

nodejs 18 is already in the base image
Change-type: minor

Remove runtime step to install node

---

runner/balena.sh
runner/docker-compose.test.yml

Set default runner group

---

runner/jammy/amd64/eget.toml
runner/jammy/arm/eget.toml
runner/jammy/arm64/eget.toml

Update runner version

---

runner/balena.sh
runner/docker-compose.test.yml

Fix home permissions

---

runner/Dockerfile

Install eget v1.3.3 from binary releases

---

.github/workflows/flowzone.yml

Prevent duplicate workflows from breaking branch protection

---

.github/workflows/flowzone.yml

Publish docker tags for each platform

---

runner/jammy/amd64/eget.toml
runner/jammy/arm/eget.toml
runner/jammy/arm64/eget.toml

Also switch to the docker variant of runner-container-hooks
Change-type: minor

Update actions/runner and runner-container-hooks

---

runner/docker-compose.test.yml

Wait for runner to register as online during tests

---

runner/Dockerfile

This makes it easier to get pre-release features
and simplifies the Dockerfile.
Change-type: patch

Build eget from source

---

runner/docker-compose.test.yml
runner/start-runner.sh

Test that the runner process is using the github user environment

---

runner/docker-compose.test.yml
runner/start-runner.sh

Handle whitespaces in labels

---

runner/Dockerfile
runner/docker-compose.test.yml
runner/jammy/amd64/eget.toml
runner/jammy/packages.txt
runner/packages.txt

add balena, aws and gh CLIs

---

runner/Dockerfile

switch to if/then block

---

runner/docker-compose.test.yml
runner/start-runner.sh

Remove balena uuid label as runners are not being picked up

---

runner/docker-compose.test.yml
runner/start-runner.sh

Restore balena device uuid custom label

---

runner/Dockerfile
runner/packages.txt

Install zstd

---

README.md
runner/docker-compose.test.yml
runner/start-runner.sh

Fix tmpfs syntax but keep execute bit

---

runner/Dockerfile
runner/jammy/amd64/eget.toml
runner/jammy/arm64/eget.toml

balena-cli ARM binaries

---

runner/Dockerfile
runner/tmpfs-exec.sh

Remount tmpfs volumes with execute bit before starting s6

---

runner/Dockerfile
runner/jammy/amd64/eget.toml
runner/jammy/arm/eget.toml
runner/jammy/arm64/eget.toml

Allow Renovate to manage packages installed via eget

---

runner/Dockerfile
runner/docker-compose.test.yml
runner/packages.txt
runner/start-runner.sh
runner/tmpfs-exec.sh

This aligns with the hosted github runners and fixes some issues with hardcoded home paths /home/runner in actions.
Change-type: major

Change runtime user from github to runner

---

runner/tmpfs-exec.sh

Unmount any existing tmpfs binds that may exist on startup

---

runner/Dockerfile
runner/jammy/amd64/eget.toml
runner/jammy/arm/eget.toml
runner/jammy/arm64/eget.toml

Install specific npm version controlled via Renovate

---

runner/Dockerfile
runner/jammy/amd64/eget.toml
runner/jammy/arm64/eget.toml

Remove the hardcoded v prefix in balena-cli releases

---

runner/Dockerfile

Change-type: patch
See: https://github.com/product-os/flowzone/pull/731

Install podman, buildah, and skopeo from ubuntu 21 repos

---

runner/Dockerfile
runner/s6-overlay/scripts/get-token

Install github token npm package at build time

---

runner/s6-overlay/scripts/get-token
runner/s6-overlay/scripts/start-runner

Fallback to GitHub PAT for enterprise runner registration

---

runner/Dockerfile
runner/docker-compose.test.yml
runner/docker-hc

Run e2e tests from a sidecar service

---

runner/Dockerfile
runner/config/eget.aarch64.toml
runner/config/eget.x86_64.toml

Remove actions hooks and powershell release tag prefix

---

.github/workflows/flowzone.yml
runner/s6-overlay/s6-rc.d/runner/run

Silence the error when board_name is unknown

---

runner/s6-overlay/scripts/functions

Add CPU model name to automatic runner labels

---

runner/s6-overlay/scripts/register

> QoL improvement debugging jobs not starting
https://balena.fibery.io/Security/Information_Security_and_Reliability_Incident/aarch64-self-hosted-runners-doesn't-pick-up-jobs-115

patch: Check GH token limits and warn if depleted
